function schimbare_spre_ca(Fig, A,f,B, N, VA, RL, ic, RC, VB, Av, VRE, Vbe_on, VCE)
 

% Șterge toate controalele din fereastra curentă
% Șterge toate controalele UI din fereastră (imaginea și butoanele)
delete(findobj(Fig, 'Type', 'UIControl'));  % Șterge butoanele și alte controale UI

% Șterge imaginea (dacă există)
delete(findobj(Fig, 'Type', 'Image'));

% Șterge grupul de radio butoane (dacă există)
delete(findobj(Fig, 'Type', 'uibuttongroup'));
clf;


%...................................................%
% Citește imaginea
img = imread('Schema de semnal mic - Curent Alternativ.jpeg');

% Creează un axes în colțul din stânga sus
ax = axes('Position', [0, 0.5, 0.5, 0.5]);  % Poziționează axes în colțul stânga sus al ferestrei

% Afișează imaginea pe axes
imshow(img, 'Parent', ax);  % Afișează imaginea pe axes
axis off;  % Ascunde axele pentru o prezentare mai curată


%...................................................%
%VERIFICARI 

if RL<0.0001
    RL=1
end
if N<0.0001
    N=1
end
if f<0.0001
    f=1
end


%...................................................%
%ECUATII

T=1./f;
t=0:T/100:N*T;
Si=A.*sin(2*pi*f*t); %expresia semnalului de intrare

%parametri de semnal mic

gm= 40 *ic

rbe= B./gm
rce=VA/ic

Rp1=(rce.*RC)./(rce+RC)
Rp2=(Rp1.*RL)./(Rp1+RL)
Av=-gm.*Rp2

So=Av.*Si  %expresia semnalului de iesire

Sb=VB+Si 
Sce=VCE+So
%...................................................%
% Verificarea saturatiei

if min(Sce) < 0.2
    % Dacă condiția este îndeplinită, schimbăm amplitudinea 
    A = (0.2-VCE)./Av;
    Sce=VCE+So
end

disp(['Minimul lui Sce este: ', num2str(min(Sce))]);  % Verifică valoarea minimă din Sce
disp(['Maximul lui Sce este: ', num2str(max(Sce))]);  % Verifică valoarea maximă din Sc

%...................................................%
%BUTOANE DE TIP EDIT

RadioGroup=uibuttongroup('Visible','on',... 
'BackgroundColor','#fdfdfd',... 
'ForegroundColor','black',... 
'Title','Parametri:',... 
'FontSize',20,... 
'TitlePosition','centertop',... 
'Tag','radiobutton',... 
'Position',[0.5, 0.5, 0.5, 0.5]); 

uicontrol('Style','text',...             
    'Units','normalized',...            %Text pt A                                                        
    'Position',[0 0.8 0.5 .18],...           
    'BackgroundColor','#f0f0f0',...           
    'string','A [V]',... 
    'FontSize', 15,...
    'Callback','',... 
    'Parent',RadioGroup);
%...................................................%

uicontrol('Style','edit',...            %Edit pt A           
    'Units','normalized',...           
    'Position',[0.5 0.80 0.5 .18],...           
    'String',A,...   
    'FontSize', 15,...
    'Callback','A=str2num(get(gco,''String''))',...
    'Parent',RadioGroup);


uicontrol('Style','text',...            %Text pt f          
    'Units','normalized',...           
    'Position',[0 0.6 0.5 .18],...           
    'BackgroundColor','#f0f0f0',...  
    'string','f [KHz]',... 
    'FontSize', 15,...
    'Callback','',... 
    'Parent',RadioGroup);        
uicontrol('Style','edit',...            %Edit pt f          
     'Units','normalized',...           
    'Position',[0.5 0.60 0.5 .18],...           
    'String',f,...    
    'FontSize', 15,...
    'Callback','f=str2num(get(gco,''String''))',...
    'Parent',RadioGroup);

uicontrol('Style','text',...            %Text pentru N-  nr de perioade           
    'Units','normalized',...           
    'Position',[0 0.4 0.5 .18],...           
    'BackgroundColor','#f0f0f0',...           
    'string','N',... 
    'FontSize', 15,...
    'Callback','',... 
    'Parent',RadioGroup);        
uicontrol('Style','edit',...            %Edit pt N            
    'Units','normalized',...           
    'Position',[0.5 0.40 0.5 .18],...           
    'String',N,...   
    'FontSize', 15,...
    'Callback','N=str2num(get(gco,''String''))',...
    'Parent',RadioGroup);


uicontrol('Style','text',...            %Text pentru RL           
    'Units','normalized',...           
    'Position',[0 0.2 0.5 .18],...           
    'BackgroundColor','#f0f0f0',...          
    'string','RL[Kohm]',... 
    'FontSize', 15,...
    'Callback','',... 
    'Parent',RadioGroup);        
uicontrol('Style','edit',...            %Edit pt RL           
    'Units','normalized',...           
    'Position',[0.5 0.20 0.5 .18],...           
    'String',RL,...  
    'FontSize', 15,...
    'Callback','RL=str2num(get(gco,''String''))',...
    'Parent',RadioGroup); 


%...................................................%
%BUTOANE PENTRU RECALCULARE SI INTORCERE LA MENIU

uicontrol('Style','pushbutton',...              
    'Units','normalized',...           
    'Position',[0.8 0 0.2 .1],...           
    'string','INAPOI LA SCHEMA DE CURENT CONTINUU',...   
    'FontWeight','bold',...
    'Callback','schimbare_spre_cc(Fig, VAl,Vbe_on, B, RB1, RB2, RC, RE, ic, VB, VBE, VRE,tipr,valr, VCE ) ');

uicontrol('Style','pushbutton',...              
    'Units','normalized',...           
    'Position',[0.4 0 0.2 .1],...           
    'string','SPRE CRONOGRAME',...   
    'FontWeight','bold',...
    'Callback','schimbare_spre_cronograme(Fig, N,f, Si,So,Sb, t, Av, A, VB)'); 

uicontrol('Style','pushbutton',...              
    'Units','normalized',...           
    'Position',[0 0 0.2 .1],...           
    'string','RECALCULARE',...   
    'FontWeight','bold',...
    'Callback','schimbare_spre_ca(Fig, A,f,B, N, VA, RL, ic, RC, VB, Av, VRE, Vbe_on, VCE)');
%...................................................%

%BUTOANE DE TIP TEXT PENTRU AFISAREA REZULTATULUI FINAL


uicontrol('Style','text',...                    
    'Units','normalized',...           
    'Position',[0.25 0.4 0.5 .04],...                      
    'String', ['Valorile pentru gm, rce si rbe:  ', num2str(gm), ',  ', num2str(rce), ',  ', num2str(rbe)],... 
    'FontSize', 15,...
    'BackgroundColor','#f0f0f0',... 
    'Callback',''); 

uicontrol('Style','text',...                    
    'Units','normalized',...           
    'Position',[0.25 0.35 0.5 .04],...                      
    'String', ['Valoarea amplificarii semnalului este:  ', num2str(Av)],... 
    'FontSize', 15,...
    'BackgroundColor','#f0f0f0',... 
    'Callback',''); 

uicontrol('Style','text',...                    
    'Units','normalized',...           
    'Position',[0.25 0.3 0.5 .04],...                      
    'String', ['Expresia semnalui vi:  ', num2str(A), 'sin(', num2str(2*f), 'πt)'],... 
    'FontSize', 15,...
    'BackgroundColor','#f0f0f0',... 
    'Callback',''); 

uicontrol('Style','text',...                    
    'Units','normalized',...           
    'Position',[0.25 0.25 0.5 .04],...                      
    'String', ['Expresia semnalui vo:  ',num2str(A*Av), 'sin(', num2str(2*f), 'πt)'],... 
    'FontSize', 15,...
    'BackgroundColor','#f0f0f0',... 
    'Callback',''); 

uicontrol('Style','text',...                    
    'Units','normalized',...           
    'Position',[0.25 0.2 0.5 .04],...                      
    'String', ['Expresia semnalui vB:  ', num2str(VB), '+', num2str(A), 'sin(', num2str(2*f), 'πt)'],... 
    'FontSize', 15,...
    'BackgroundColor','#f0f0f0',... 
    'Callback',''); 

uicontrol('Style','text',...                    
    'Units','normalized',...           
    'Position',[0.25 0.15 0.5 .04],...                      
    'String', ['Expresia semnalui vce:  ', num2str(VCE), '+', num2str(Av*A), 'sin(', num2str(2*f), 'πt)'],... 
    'FontSize', 15,...
    'BackgroundColor','#f0f0f0',... 
    'Callback','');

%...................................................%
assignin('base', 'N', N); % Actualizează în Workspace
assignin('base', 'f', f); % Actualizează în Workspace
assignin('base', 'RL', RL); % Actualizează în Workspace
assignin('base', 't', t); % Actualizează în Workspace
assignin('base', 'Si', Si); % Actualizează în Workspace
assignin('base', 'Av', Av); % Actualizează în Workspace
assignin('base', 'So', So); % Actualizează în Workspace
assignin('base', 'Sb', Sb); % Actualizează în Workspace
assignin('base', 'A', A); % Actualizează în Workspace
end