function schimbare_initiala(Fig)

    % Șterge toate controalele din fereastra curentă
    % Șterge toate controalele UI din fereastră (imaginea și butoanele)
    delete(findobj(Fig, 'Type', 'UIControl'));  % Șterge butoanele și alte controale UI
    
    % Șterge imaginea (dacă există)
    delete(findobj(Fig, 'Type', 'Image'));
    
    % Șterge grupul de radio butoane (dacă există)
    delete(findobj(Fig, 'Type', 'uibuttongroup'));
    
%...................................................%

uicontrol('Style','pushbutton',...                 
    'Units','normalized',...           
    'Position',[0.2 0.55 0.6 .3],...           
    'string','AMPLIFICATOR CU TRANZISTOR BIPOLAR ',... 
    'FontSize',15,... 
    'Callback','schimbare_spre_schema_circuit(Fig)');
  

uicontrol('Style','pushbutton',...                 
    'Units','normalized',...           
    'Position',[0.2 0.15 0.6 .3],...
    'FontSize',15,... 
    'string','CLOSE',...           
    'Callback','close');

end