
function schimbare_spre_cc(Fig, VAl,Vbe_on, B, RB1, RB2, RC, RE, ic, VB, VBE, VRE,tipr,valr, VCE )


%...................................................%

% Șterge toate controalele din fereastra curentă
% Șterge toate controalele UI din fereastră (imaginea și butoanele)
delete(findobj(Fig, 'Type', 'UIControl'));  % Șterge butoanele și alte controale UI

% Șterge imaginea (dacă există)
delete(findobj(Fig, 'Type', 'Image'));

% Șterge grupul de radio butoane (dacă există)
delete(findobj(Fig, 'Type', 'uibuttongroup'));


%...................................................%

% Citește imaginea
img = imread('Schema de Curent Continuu.jpeg');

% Creează un axes în colțul din stânga sus
ax = axes('Position', [0, 0.5, 0.5, 0.5]);  % Poziționează axes în colțul stânga sus al ferestrei

% Afișează imaginea pe axes
imshow(img, 'Parent', ax);  % Afișează imaginea pe axes
axis off;  % Ascunde axele pentru o prezentare mai curată


%...................................................%
%VERIFICARI PENTRU VALORILE REZISTENTELOR

if RB1<0.0001
    RB1=1
end

if RB2<0.0001
    RB2=1
end

if RC<0.0001
    RC=1
end

if RE<0.0001
    RE=1
end

if VAl<0.0001
    VAl=1

end

%...................................................%

%ECUATIILE DE CALCULARE A PUNCTULUI STATIC DE FUNCTIONARE CU PRESUPUNEREA
%CA TRANZISTORUL ESTE IN AF

VB=(RB2./(RB2+RB1)).*VAl

VRE=VB-Vbe_on

ic=VRE./RE

VCE=VAl-ic.*(RC+RE)

%...................................................%
%VERIFICARI PENTRU VALORILE PARAMETRILOR PUNCTULUI STATIC DE FUNCTIONARE
if (VCE<0.2 || ic<0)
    RC=1;RE=1;RB1=1;RB2=1;VAl=2;
    VB=(RB2./(RB2+RB1)).*VAl
VRE=VB-Vbe_on

ic=VRE./RE
VCE=VAl-ic.*(RC+RE)

end
%...................................................%
%BUTOANE DE TIP EDIT

bg=uibuttongroup('Visible','on',... 
'BackgroundColor','#fdfdfd',... 
'ForegroundColor','black',... 
'Title','Parametri:',...d9eafd 
'FontSize',20,... 
'TitlePosition','centertop',... 
'Tag','radiobutton',... 
'Position',[0.5, 0.5, 0.5, 0.5]); 

uicontrol('Style','text',...             
    'Units','normalized',...            %Text pt VAl                                                         
    'Position',[0 0.8 0.5 .18],...           
    'BackgroundColor','#f0f0f0',...           
    'string','VAl [V]',... 
    'FontSize', 15,...
    'Callback','',... 
    'Parent',bg);
uicontrol('Style','edit',...            %Edit pt VAl            
    'Units','normalized',...           
    'Position',[0.5 0.80 0.5 .18],...           
    'String',VAl,...   
    'FontSize', 15,...
    'Callback','VAl=str2num(get(gco,''String''))',...
    'Parent',bg);


uicontrol('Style','text',...            %Text pt RB1           
    'Units','normalized',...           
    'Position',[0 0.6 0.5 .18],...           
    'BackgroundColor','#f0f0f0',...  
    'string','RB1[Kohm]',... 
    'FontSize', 15,...
    'Callback','',... 
    'Parent',bg);        
uicontrol('Style','edit',...            %Edit pt RB1           
     'Units','normalized',...           
    'Position',[0.5 0.60 0.5 .18],...           
    'String',RB1,...    
    'FontSize', 15,...
    'Callback','RB1=str2num(get(gco,''String''))',...
    'Parent',bg);
%.....................................................%


uicontrol('Style','text',...            %Text pentru RB2           
    'Units','normalized',...           
    'Position',[0 0.4 0.5 .18],...           
    'BackgroundColor','#f0f0f0',...           
    'string','RB2[Kohm]',... 
    'FontSize', 15,...
    'Callback','',... 
    'Parent',bg);        
uicontrol('Style','edit',...            %Edit pt RB2            
    'Units','normalized',...           
    'Position',[0.5 0.40 0.5 .18],...           
    'String',RB2,...   
    'FontSize', 15,...
    'Callback','RB2=str2num(get(gco,''String''))',...
    'Parent',bg);
%.....................................................%

uicontrol('Style','text',...            %Text pentru RC           
    'Units','normalized',...           
    'Position',[0 0.2 0.5 .18],...           
    'BackgroundColor','#f0f0f0',...          
    'string','RC[Kohm]',... 
    'FontSize', 15,...
    'Callback','',... 
    'Parent',bg);
%.....................................................%
%Popup menu pentru RC

    serie_menu = uicontrol('Style', 'popupmenu', ...
        'Units', 'normalized', ...
        'Position', [0.5, 0.2, 0.25, 0.18], ...
        'String', {'Serii'}, ...
        'FontSize', 15, ...
        'BackgroundColor','#f0f0f0',...
        'ForegroundColor', 'k', ...
        'Callback', 'update_valori',... 
         'Parent',bg);

    % Meniu pentru selectarea valorii
    valoare_menu = uicontrol('Style', 'popupmenu', ...
        'Units', 'normalized', ...
        'Position', [0.75, 0.2, 0.25, 0.18], ...
        'String', {'valoare'}, ...
        'FontSize', 15, ...
        'BackgroundColor','#f0f0f0',...
        'ForegroundColor', 'k', ...
        'Callback', 'actualizeaza_RC',... 
          'Parent',bg);
%.....................................................%
uicontrol('Style','edit',...            %Edit pt RC           
    'Units','normalized',...           
    'Position',[0.5 0.2 0.5 .09],...           
    'String',RC,...    
    'FontSize', 15,...
    'ForegroundColor', '#bdbdbd', ...
    'Callback','RC=str2num(get(gco,''String''))',...
    'Parent',bg);
%...................................................%

uicontrol('Style','text',...            %Text pentru RE           
    'Units','normalized',...           
    'Position',[0 0 0.5 .18],...                      
    'string','RE[Kohm]',... 
    'FontSize', 15,...
    'BackgroundColor','#f0f0f0',... 
    'Callback','',... 
    'Parent',bg);        
uicontrol('Style','edit',...            %Edit pt RE           
    'Units','normalized',...           
    'Position',[0.5 0 0.5 .18],...           
    'String',RE,...    
    'FontSize', 15,...
    'Callback','RE=str2num(get(gco,''String''))',...
    'Parent',bg);
%...................................................%

%BUTOANE PENTRU RECALCULARE, SCHEMA DE SEMNAL MIC SI INTORCERE LA MENIU

uicontrol('Style','pushbutton',...              
    'Units','normalized',...           
    'Position',[0.8 0 0.2 .1],...           
    'string','INAPOI',...   
    'FontWeight','bold',...
    'Callback','schimbare_spre_schema_circuit(Fig)'); 

uicontrol('Style','pushbutton',...              
    'Units','normalized',...           
    'Position',[0.4 0 0.2 .1],...           
    'string','SPRE SCHEMA DE SEMNAL MIC',...   
    'FontWeight','bold',...
    'Callback','schimbare_spre_ca(Fig, A,f,B, N, VA, RL, ic, RC, VB, Av, VRE, Vbe_on, VCE)'); 

uicontrol('Style','pushbutton',...              
    'Units','normalized',...           
    'Position',[0 0 0.2 .1],...           
    'string','RECALCULARE',...   
    'FontWeight','bold',...
    'Callback','schimbare_spre_cc(Fig, VAl,Vbe_on, B, RB1, RB2, RC, RE, ic, VB, VBE, VRE,tipr,valr, VCE ) '); 
%...................................................%

%BUTOANE DE TIP TEXT PENTRU AFISAREA REZULTATULUI FINAL

uicontrol('Style','text',...                     
    'Units','normalized',...           
    'Position',[0.25 0.3 0.4 .1],...                      
    'string','Punctul static de functionare Q(VCE, ic) este egal cu: ',... 
    'FontSize', 15,...
    'BackgroundColor','#f0f0f0',... 
    'Callback',''); 

uicontrol('Style','text',...                    
    'Units','normalized',...           
    'Position',[0.65 0.3 0.1 .1],...                      
    'String', ['(', num2str(VCE), ', ', num2str(ic), ')'],... 
    'FontSize', 15,...
    'BackgroundColor','#f0f0f0',... 
    'Callback',''); 

uicontrol('Style','text',...                    
    'Units','normalized',...           
    'Position',[0.25 0.15 0.5 .1],...                      
    'String', ['Valoarea lui VB este:   ', num2str(VB)],... 
    'FontSize', 15,...
    'BackgroundColor','#f0f0f0',... 
    'Callback',''); 
%...................................................%

assignin('base', 'VAl', VAl); % Actualizează în Workspace
assignin('base', 'RB1', RB1); % Actualizează în Workspace
assignin('base', 'RB2', RB2); % Actualizează în Workspace
assignin('base', 'RC', RC); % Actualizează în Workspace
assignin('base', 'RE', RE); % Actualizează în Workspace
assignin('base', 'ic', ic); % Actualizează în Workspace
assignin('base', 'VB', VB); % Actualizează în Workspace
assignin('base', 'VRE', VRE); % Actualizează în Workspace
assignin('base', 'VCE', VCE); % Actualizează în Workspace
end


